//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AeraHack2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HackWell
    {
        public decimal cmpl_fac_id { get; set; }
        public string cmpl_fac_nme { get; set; }
        public string well_api_nbr { get; set; }
        public string fac_state_type_desc { get; set; }
        public string prim_purp_type_desc { get; set; }
        public string prim_prdt_matl_type_desc { get; set; }
        public string svc_stat_indc { get; set; }
        public string PROD_MFLD_FAC_NME { get; set; }
    }
}
