//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AeraHack2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HackWell
    {
        public decimal cmpl_fac_id { get; set; }
        public string cmpl_fac_nme { get; set; }
    }
}
