//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AeraHack2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_PumpingUnitInspections
    {
        public string Asset { get; set; }
        public int WellFacID { get; set; }
        public string WellName { get; set; }
        public System.DateTime InspectionDate { get; set; }
        public string InspectorName { get; set; }
        public string UnitMatchSAP { get; set; }
        public string UnitSAPNo { get; set; }
        public string UnitMfr { get; set; }
        public string UnitSN { get; set; }
        public string UnitAPI { get; set; }
        public string UnitStyle { get; set; }
        public string MotorMatchSAP { get; set; }
        public string MotorSAPNo { get; set; }
        public string MotorMfr { get; set; }
        public string MotorSN { get; set; }
        public string MotorHP { get; set; }
        public string MotorFrame { get; set; }
        public string MotorRPM { get; set; }
        public string MotorSheaveSize { get; set; }
        public string MotorNumberBelts { get; set; }
        public string MotorBeltSize { get; set; }
        public string GearboxSAPNumber { get; set; }
        public string GearboxSerialNumber { get; set; }
        public string GearboxSheaveSize { get; set; }
        public string GearboxRatio { get; set; }
        public string CBRotation { get; set; }
        public string CBCranks { get; set; }
        public string CBLeftMainLead { get; set; }
        public string CBLeftAux1Lead { get; set; }
        public string CBLeftAux2Lead { get; set; }
        public string CBLeftMainLag { get; set; }
        public string CBLeftAux1Lag { get; set; }
        public string CBLeftAux2Lag { get; set; }
        public string CBRightAux1Lead { get; set; }
        public string CBRightAux2Lead { get; set; }
        public string CBRightMainLag { get; set; }
        public string CBRightAux1Lag { get; set; }
        public string CBRightAux2Lag { get; set; }
        public string GearboxGearsCondition { get; set; }
        public string GearboxGearsComment { get; set; }
        public Nullable<int> GearboxGearsReplacedIndicator { get; set; }
        public Nullable<int> GearboxGearsSealLeakIndicator { get; set; }
        public string GearboxLeakingIndicator { get; set; }
        public string CranksCondition { get; set; }
        public string CranksComment { get; set; }
        public Nullable<int> CranksReplacedIndicator { get; set; }
        public string CounterweightsCondition { get; set; }
        public string CounterweightsComment { get; set; }
        public Nullable<int> CounterweightsReplacedIndicator { get; set; }
        public string LeftWristpinCondition { get; set; }
        public string LeftWristpinComment { get; set; }
        public Nullable<int> LeftWristpinReplacedIndicator { get; set; }
        public Nullable<int> LeftWristpinSealLeakIndicator { get; set; }
        public string RightWristpinCondition { get; set; }
        public string RightWristpinComment { get; set; }
        public Nullable<int> RightWristpinReplacedIndicator { get; set; }
        public Nullable<int> RightWristpinSealLeakIndicator { get; set; }
        public string CenterBearingCondition { get; set; }
        public string CenterBearingComment { get; set; }
        public Nullable<int> CenterBearingReplacedIndicator { get; set; }
        public Nullable<int> CenterBearingSealLeakIndicator { get; set; }
        public string EqualizerBearingCondition { get; set; }
        public string EqualizerBearingComment { get; set; }
        public Nullable<int> EqualizerBearingReplacedIndicator { get; set; }
        public Nullable<int> EqualizerBearingSealLeakIndicator { get; set; }
        public string BeamCondition { get; set; }
        public string BeamComment { get; set; }
        public Nullable<int> BeamReplacedIndicator { get; set; }
        public string PitmanArmsCondition { get; set; }
        public string PitmanArmsComment { get; set; }
        public Nullable<int> PitmanArmsReplacedIndicator { get; set; }
        public string SampsonPostCondition { get; set; }
        public string SampsonPostComment { get; set; }
        public Nullable<int> SampsonPostReplacedIndicator { get; set; }
        public string LadderCondition { get; set; }
        public string LadderComment { get; set; }
        public Nullable<int> LadderReplacedIndicator { get; set; }
        public string HeadCondition { get; set; }
        public string HeadComment { get; set; }
        public Nullable<int> HeadReplacedIndicator { get; set; }
        public string BridleCondition { get; set; }
        public string BridleComment { get; set; }
        public Nullable<int> BridleReplacedIndicator { get; set; }
        public string GreaseLinesCondition { get; set; }
        public string GreaseLinesComment { get; set; }
        public Nullable<int> GreaseLinesReplacedIndicator { get; set; }
        public string BeltGuardCondition { get; set; }
        public string BeltGuardComment { get; set; }
        public Nullable<int> BeltGuardReplacedIndicator { get; set; }
        public string BeltsCondition { get; set; }
        public string BeltsComment { get; set; }
        public Nullable<int> BeltsReplacedIndicator { get; set; }
        public string MotorCondition { get; set; }
        public string MotorComment { get; set; }
        public Nullable<int> MotorReplacedIndicator { get; set; }
        public string BrakeCondition { get; set; }
        public string BrakeComment { get; set; }
        public Nullable<int> BrakeReplacedIndicator { get; set; }
        public string UnitGuardCondition { get; set; }
        public string UnitGuardComment { get; set; }
        public Nullable<int> UnitGuardReplacedIndicator { get; set; }
        public string StructureBoltsCondition { get; set; }
        public string StructureBoltsComment { get; set; }
        public Nullable<int> StructureBoltsReplacedIndicator { get; set; }
        public string UnitPadCondition { get; set; }
        public string UnitPadComment { get; set; }
        public Nullable<int> UnitPadReplacedIndicator { get; set; }
        public string ElectricPanelHOACondition { get; set; }
        public string ElectricPanelHOAComment { get; set; }
        public Nullable<int> ElectricPanelHOAReplacedIndicator { get; set; }
        public string HorseHeadCondition { get; set; }
        public string HorseHeadComment { get; set; }
        public string DataPlateCondition { get; set; }
        public string DataPlateComment { get; set; }
        public string WellSignCondition { get; set; }
        public string WellSignComment { get; set; }
        public string TubingRotatorCondition { get; set; }
        public string TubingRotatorComment { get; set; }
        public string RodRotatorCondition { get; set; }
        public string RodRotatorComment { get; set; }
        public string CenterBearingsCondition { get; set; }
        public string CenterBearingsComment { get; set; }
        public string TailBearingsCondition { get; set; }
        public string TailBearingsComment { get; set; }
        public string WristPinsCondition { get; set; }
        public string WristPinsComment { get; set; }
        public string GearboxOilLevelCondition { get; set; }
        public string GearboxOilLevelComment { get; set; }
        public string GearboxGalsOilAdded { get; set; }
        public string BrakeCableCondition { get; set; }
        public string BrakeCableComment { get; set; }
        public string BrakeHingesCondition { get; set; }
        public string BrakeHingesComment { get; set; }
        public string CleanAreaCondition { get; set; }
        public string CleanAreaComment { get; set; }
        public string CleanUnitCondition { get; set; }
        public string CleanUnitComment { get; set; }
        public string SAPNumOnUnitCondition { get; set; }
        public string SAPNumOnUnitComment { get; set; }
        public string SAPNumOnMotorCondition { get; set; }
        public string SAPNumOnMotorComment { get; set; }
        public string LubeStickersAppliedCondition { get; set; }
        public string LubeStickersAppliedComment { get; set; }
        public string DustCapsCondition { get; set; }
        public string DustCapsComment { get; set; }
        public string GeneralCmnts { get; set; }
    }
}
